<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <PackageReadmeFile>ClientSettingsUpdater.Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Konfidence.Mail\Konfidence.Mail.csproj" />
    <ProjectReference Include="..\..\Konfidence.SqlHostProvider\Konfidence.SqlHostProvider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="MailClientSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SqlClientSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClientSettingsUpdater.UnitTest" />
  </ItemGroup>


  <ItemGroup>
    <None Include="../../ClientSettingsUpdater.Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
