<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Konfidence.BaseData</RootNamespace>
    <AssemblyName>Konfidence.BaseDatabaseClasses</AssemblyName>
    <PackageReadmeFile>Konfidence.BaseDatabaseClasses.Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Konfidence.BaseClasses\Konfidence.BaseClasses.csproj" />
    <ProjectReference Include="..\Konfidence.DataBaseInterface\Konfidence.DatabaseInterface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Konfidence.BaseDatabaseClasses.UnitTest" />
    <InternalsVisibleTo Include="Konfidence.MenuClasses.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>


  <ItemGroup>
    <None Include="../Konfidence.BaseDatabaseClasses.Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
