<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Konfidence.UtilHelper\Konfidence.UtilHelper.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Konfidence.MsBuild.UnitTest" />
	</ItemGroup>

</Project>
