<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<!--<TargetFrameworks>net10.0</TargetFrameworks>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" Version="8.10.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="MSTest" Version="4.3.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Konfidence.Security\Konfidence.Security.csproj" />
		<ProjectReference Include="..\..\Tools\Konfidence.TestTools\Konfidence.TestTools.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SqlClientSettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
	</ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
    <NoWarn>1701;1702;CA1416;CA1860</NoWarn>
  </PropertyGroup>
</Project>
