<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Konfidence.TesTools</RootNamespace>
	  <AssemblyName>Konfidence.TestTools</AssemblyName>
	  <PackageReadmeFile>Konfidence.TestTools.Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Konfidence.SqlHostProvider\Konfidence.SqlHostProvider.csproj" />
  </ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
	</ItemGroup>

  <ItemGroup>
    <None Include="../../Konfidence.TestTools.Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
